<?php use App\Support\App;App::requireAdmin();$db=App::db();$levels=$db->query('SELECT code,name FROM user_levels ORDER BY sort_order')->fetchAll();$title='Add Product';require __DIR__.'/../layouts/head.php';require __DIR__.'/../components/app_start.php';?><div class="flex items-center gap-3"><a href="/admin/products" class="btn !p-2"><i data-lucide="arrow-left"></i></a><div><h1 class="page-title">Add product</h1><p class="page-sub">Buat layanan IMEI baru.</p></div></div><form id="product-form" class="saas-card p-5 sm:p-6 mt-6 space-y-6 max-w-4xl"><div class="grid sm:grid-cols-2 gap-4"><label class="text-sm font-semibold">Product name<input class="field mt-2" name="name" placeholder="Contoh: CEIR Check" required></label><label class="text-sm font-semibold">Product code<input class="field mt-2 font-mono" name="code" placeholder="CEIR_CHECK" required></label></div><label class="text-sm font-semibold block">Description<textarea class="field mt-2" name="description" rows="3" placeholder="Deskripsi layanan"></textarea></label><div class="grid sm:grid-cols-2 gap-4"><label class="text-sm font-semibold">Provider<select class="field mt-2" name="provider_type"><option value="manual">Manual / WhatsApp</option><option value="ceirgo">CeirGo API</option></select></label><label class="text-sm font-semibold">Processing time<input class="field mt-2" name="processing_time" placeholder="5-30 minutes"></label><label class="text-sm font-semibold">Provider service ID<input class="field mt-2" name="provider_service_id"></label><label class="text-sm font-semibold">Provider service code<input class="field mt-2" name="provider_service_code"></label><label class="text-sm font-semibold">Provider cost<input class="field mt-2" type="number" step="0.01" min="0" name="provider_cost" value="0"></label><label class="text-sm font-semibold">WhatsApp Group ID<input class="field mt-2" name="whatsapp_group_id" placeholder="120363xxxx@g.us"></label></div><div><div class="font-semibold">Selling prices</div><p class="text-xs text-zinc-500 mt-1">Harga untuk masing-masing level akun.</p><div class="grid sm:grid-cols-2 lg:grid-cols-3 gap-3 mt-3"><?php foreach($levels as $l):?><label class="text-xs font-semibold"><?=htmlspecialchars($l['name'])?><input class="field mt-1" type="number" step="0.01" min="0" name="price_<?=htmlspecialchars($l['code'])?>" value="0" required></label><?php endforeach?></div></div><div class="grid sm:grid-cols-3 gap-3"><label class="toggle-row"><input type="checkbox" name="ceir_check_enabled" value="1" checked>CEIR precheck</label><label class="toggle-row"><input type="checkbox" name="auto_refund" value="1" checked>Auto refund</label><label class="toggle-row"><input type="checkbox" name="is_active" value="1" checked>Product active</label></div><div id="save-error" class="hidden p-3 rounded-xl text-sm border"></div><button id="save-btn" type="submit" class="btn btn-dark w-full sm:w-auto"><i data-lucide="save"></i>Save product</button></form><script>
(function(){
 const form=document.getElementById('product-form'),btn=document.getElementById('save-btn'),err=document.getElementById('save-error');
 form.addEventListener('submit',async function(e){
  e.preventDefault();err.classList.add('hidden');btn.disabled=true;btn.textContent='Saving...';
  const fd=new FormData(form),data={prices:{}};
  for(const [k,v] of fd.entries()){if(k.startsWith('price_'))data.prices[k.substring(6)]=v;else data[k]=v}
  ['ceir_check_enabled','auto_refund','is_active'].forEach(k=>data[k]=fd.has(k)?1:0);
  try{
   const res=await fetch('/api/admin/products',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json','Accept':'application/json','X-CSRF-Token':'<?=App::csrf()?>'},body:JSON.stringify(data)});
   const text=await res.text();let json;try{json=JSON.parse(text)}catch(x){throw new Error('HTTP '+res.status+' — '+text.substring(0,250))}
   if(!res.ok||!json.ok)throw new Error(json.message||('HTTP '+res.status));
   location.href='/admin/products?created=1';
  }catch(x){err.textContent=x.message;err.classList.remove('hidden');if(window.Swal)Swal.fire('Gagal menambah produk',x.message,'error')}
  finally{btn.disabled=false;btn.innerHTML='<i data-lucide="save"></i> Save product';if(window.lucide)lucide.createIcons()}
 });
})();
</script><?php require __DIR__.'/../components/app_end.php';require __DIR__.'/../layouts/foot.php';?>