<?php
namespace App\Services;use App\Config\Database;use App\Services\Provider\CeirGoProvider;
final class OrderService{
 public function create(int $uid,int $pid,string $imei):array{
  if(!preg_match('/^\d{15}$/',$imei))throw new \InvalidArgumentException('IMEI harus tepat 15 digit angka');$db=Database::get();$oid=0;
  $db->beginTransaction();try{$q=$db->prepare('SELECT p.*,pp.price FROM products p JOIN users u ON u.id=? JOIN product_prices pp ON pp.product_id=p.id AND pp.level_id=u.level_id WHERE p.id=? AND p.is_active=1 AND u.status="active"');$q->execute([$uid,$pid]);$p=$q->fetch();if(!$p)throw new \RuntimeException('Produk tidak tersedia untuk akun ini');$no='ORD-'.date('ymdHis').'-'.strtoupper(bin2hex(random_bytes(3)));$db->prepare('INSERT INTO orders(order_number,user_id,product_id,imei,status,selling_price,provider_cost,provider_type,wa_group_id) VALUES(?,?,?,?,?,?,?,?,?)')->execute([$no,$uid,$pid,$imei,'pending',$p['price'],$p['provider_cost'],$p['provider_type'],$p['whatsapp_group_id']]);$oid=(int)$db->lastInsertId();WalletService::move($db,$uid,-(float)$p['price'],'order',$no,'order:'.$oid);$db->commit();
   if((int)$p['ceir_check_enabled']===1){$db->prepare('UPDATE orders SET status="ceir_check" WHERE id=?')->execute([$oid]);$c=(new CeirService())->check($imei);$db->prepare('UPDATE orders SET ceir_status=?,ceir_raw_response=? WHERE id=?')->execute([$c['status'],json_encode($c['raw']),$oid]);if(in_array($c['status'],['REGISTERED','ROAMER'],true)){if((int)$p['auto_refund']===1)(new RefundService())->refund($oid,'CEIR '.$c['status']);else $db->prepare('UPDATE orders SET status="rejected",reject_reason=?,completed_at=NOW() WHERE id=?')->execute(['CEIR '.$c['status'],$oid]);return $this->get($oid);}if($c['status']==='ERROR'){$db->prepare('UPDATE orders SET status="pending",reject_reason="CEIR check error - retry required" WHERE id=?')->execute([$oid]);return $this->get($oid);}}
   if($p['provider_type']==='manual'){$db->prepare('UPDATE orders SET status="processing",processed_at=NOW() WHERE id=?')->execute([$oid]);return $this->get($oid);}
   $r=(new CeirGoProvider())->submit(['imei'=>$imei],$p);$remote=strtolower((string)($r['status']??'processing'));$status=in_array($remote,['success','done','completed'],true)?'success':'processing';$db->prepare('UPDATE orders SET provider_order_id=?,provider_response=?,status=?,processed_at=NOW(),completed_at=IF(?="success",NOW(),NULL) WHERE id=?')->execute([(string)($r['order_id']??$r['reference_id']??''),json_encode($r),$status,$status,$oid]);return $this->get($oid);
  }catch(\Throwable $e){if($db->inTransaction())$db->rollBack();if($oid){try{(new RefundService())->refund($oid,'Processing exception');}catch(\Throwable $ignored){}}throw $e;}
 }
 public function get(int $id):array{$q=Database::get()->prepare('SELECT * FROM orders WHERE id=?');$q->execute([$id]);return $q->fetch()?:[];}
 public function setStatus(int $id,string $status,string $reason=''):void{
  if(!in_array($status,['processing','success','rejected','cancelled'],true))throw new \InvalidArgumentException('Status invalid');
  $db=Database::get();$q=$db->prepare('SELECT o.status,o.refund_status,p.auto_refund FROM orders o JOIN products p ON p.id=o.product_id WHERE o.id=?');$q->execute([$id]);$o=$q->fetch();if(!$o)throw new \RuntimeException('Order tidak ditemukan');
  if(in_array($o['status'],['success','refunded','cancelled'],true))throw new \RuntimeException('Order final tidak dapat diubah lagi');
  if($status==='rejected'){if((int)$o['auto_refund']===1){(new RefundService())->refund($id,$reason?:'Rejected');return;}$db->prepare('UPDATE orders SET status="rejected",reject_reason=?,completed_at=NOW() WHERE id=?')->execute([$reason?:'Rejected',$id]);return;}
  $db->prepare('UPDATE orders SET status=?,processed_at=IF(?="processing",COALESCE(processed_at,NOW()),processed_at),completed_at=IF(? IN ("success","cancelled"),NOW(),completed_at) WHERE id=?')->execute([$status,$status,$status,$id]);
 }
}